apiVersion: apps/v1
kind: Deployment
metadata:
  name: whgmocdrr
spec:whgmocdrr
  replicas: 1
  selector:
    matchLabels:
      app: whgmocdrr
  template:
    metadata:
      labels:
        app: whgmocdrr
    spec:
      containers:
      - image: okteto.dev/whgmocdrr:latest
        name: whgmocdrr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ce85cd82-829c-4c90-81aa-f4c7dd0cbda0"
        - name: Vless_Path
          value: "/vl897555"
        - name: Vmess_UUID
          value: "ce85cd82-829c-4c90-81aa-f4c7dd0cbda0"
        - name: Vmess_Path
          value: "/vm674466"
        - name: Share_Path
          value: "/v2link"
